name: Forge Coverage

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

permissions: write-all

jobs:
  check:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-e15e33a07c0920189fc336391f538c3dad53da73

      - name: Install lcov
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Run coverage
        env:
          MNEMONIC: ${{ secrets.MNEMONIC_FOR_TESTS }}
        run: npm run coverage
        id: coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          artifact-name: code-coverage-report
          minimum-coverage: 60
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
